/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package homework03

import kotlin.concurrent.thread

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val topic = getTopic("kotlin")
    println(topic.pickUpTime)
}
