/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package homework03

import kotlinx.coroutines.runBlocking

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
//    val topic = getTopic("kotlin")
    runBlocking {
//        getComments("https://www.reddit.com/r/Kotlin/comments/10jm5a5/is_kotlin_scripting_dead/.json")
        saveTopic(getTopic("Kotlin"))
    }
}
